"""Timeline Service – orchestrates AnalysisResult → Timeline conversion.

This service is responsible for:
    - Converting an AnalysisResult (from AIService) into a Timeline.
    - Ensuring every high-score event becomes a TimelineEvent.
    - Assigning thumbnails to events when available.
    - Providing the filtered event lists for export.

The service does NOT call the AI.  It works with pre-analyzed data.

Pipeline position:
    AIService → AnalysisResult → TimelineService → Timeline → PromptService
"""

from __future__ import annotations

import logging
from pathlib import Path

from models.analysis import AnalysisResult
from models.event import TimelineEvent, RoadQualityScores
from models.scene import Scene
from models.timeline import Timeline

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# TimelineService
# ---------------------------------------------------------------------------

class TimelineService:
    """Convert AI analysis results into an editable Timeline.

    Every detected event with score >= 5.0 becomes a TimelineEvent.
    Events are sorted chronologically and stored in the Timeline.
    """

    def build_from_analysis(
        self,
        analysis: AnalysisResult,
        video_path: Path,
        *,
        min_score: float = 5.0,
    ) -> Timeline:
        """Build a Timeline from a completed AnalysisResult.

        Args:
            analysis: Result produced by AIService.analyze_scenes().
            video_path: Source video file path (stored for reference).
            min_score: Minimum score to include an event in the timeline.

        Returns:
            A fully populated Timeline ready for prompting and export.
        """
        events: list[TimelineEvent] = []

        # Use events already generated by AI service
        if analysis.events:
            for evt in analysis.events:
                if evt.score >= min_score:
                    events.append(evt)
        else:
            # Fallback: create TimelineEvents from FrameAnalyses
            for fa in analysis.frame_analyses:
                if fa.score >= min_score:
                    evt = TimelineEvent(
                        start_time=fa.timestamp,
                        end_time=fa.timestamp + 5.0,
                        score=fa.score,
                        description=fa.reason,
                        reason=fa.reason,
                        tags=fa.tags,
                    )
                    events.append(evt)

        # Sort chronologically
        events.sort(key=lambda e: e.start_time)

        timeline = Timeline(
            video_path=str(video_path),
            events=events,
            scenes=analysis.scenes,
        )

        logger.info(
            "Built timeline with %d events from analysis (overall_score=%.2f)",
            len(events),
            analysis.overall_score,
        )

        return timeline

    def add_events(
        self,
        timeline: Timeline,
        new_events: list[TimelineEvent],
    ) -> None:
        """Append additional events to an existing timeline.

        Mutates *timeline* in-place.
        """
        timeline.events.extend(new_events)
        timeline.events.sort(key=lambda e: e.start_time)

    def remove_events(
        self,
        timeline: Timeline,
        event_ids: list[str],
    ) -> None:
        """Remove events by ID from a timeline.

        Mutates *timeline* in-place.
        """
        id_set = set(event_ids)
        timeline.events = [e for e in timeline.events if e.event_id not in id_set]

    def get_events_by_score_range(
        self,
        timeline: Timeline,
        low: float,
        high: float,
    ) -> list[TimelineEvent]:
        """Return events whose score falls within [low, high]."""
        return [e for e in timeline.events if low <= e.score <= high]

    def get_best_n_events(
        self,
        timeline: Timeline,
        n: int,
    ) -> list[TimelineEvent]:
        """Return the top-N events by score."""
        sorted_events = sorted(timeline.events, key=lambda e: e.score, reverse=True)
        return sorted_events[:n]

    def get_total_highlight_duration(self, timeline: Timeline) -> float:
        """Sum of all event durations in seconds."""
        return sum(e.duration for e in timeline.events)