"""Script to generate model files."""

import os

def write_analysis():
    path = os.path.join("models", "analysis.py")
    lines = []
    lines.append('"""Analysis result from AI frame batch processing."""')
    lines.append("from dataclasses import dataclass")
    lines.append("")
    lines.append("")
    lines.append("")
    lines.append("@dataclass(slots=True, frozen=True)")
    lines.append("class FrameAnalysis:")
    lines.append('    """AI analysis result for a single frame or timestamp."""')
    lines.append("    timestamp: float")
    lines.append("    score: float")
    lines.append("    reason: str")
    lines.append("    tags: list[str]")
    lines.append("")
    lines.append("")
    lines.append("    @property")
    lines.append("    def star_rating(self) -> int:")
    lines.append("        if self.score >= 9.0:")
    lines.append("            return 5")
    lines.append("        if self.score >= 7.5:")
    lines.append("            return 4")
    lines.append("        if self.score >= 6.0:")
    lines.append("            return 3")
    lines.append("        if self.score >= 4.0:")
    lines.append("            return 2")
    lines.append("        return 1")
    lines.append("")
    lines.append("")
    lines.append("    @property")
    lines.append("    def star_text(self) -> str:")
    lines.append('        return "\u2b50" * self.star_rating')
    lines.append("")
    lines.append("")
    lines.append("")
    lines.append("@dataclass(slots=True, frozen=True)")
    lines.append("class AnalysisResult:")
    lines.append('    """Complete analysis result."""')
    lines.append("    overall_score: float")
    lines.append("    frame_analyses: list[FrameAnalysis]")
    lines.append("    best_moments: list[FrameAnalysis]")
    lines.append("")
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Written: {path}")


def write_highlight():
    path = os.path.join("models", "highlight.py")
    lines = []
    lines.append('"""Highlight configuration and output models."""')
    lines.append("from dataclasses import dataclass")
    lines.append("from enum import Enum")
    lines.append("")
    lines.append("")
    lines.append("")
    lines.append("class HighlightStyle(Enum):")
    lines.append('    """Style of the highlight edit."""')
    lines.append('    STANDARD = "standard"')
    lines.append('    CINEMATIC = "cinematic"')
    lines.append('    YOUTUBE = "youtube"')
    lines.append('    SHORTS = "shorts"')
    lines.append("")
    lines.append("")
    lines.append("")
    lines.append("@dataclass(slots=True, frozen=True)")
    lines.append("class HighlightConfig:")
    lines.append('    """Configuration for highlight generation."""')
    lines.append("    style: HighlightStyle = HighlightStyle.STANDARD")
    lines.append("    min_score: float = 6.0")
    lines.append("    max_duration: float = 300.0")
    lines.append("    transition_duration: float = 0.5")
    lines.append('    prompt: str = ""')
    lines.append("")
    lines.append("")
    lines.append("")
    lines.append("@dataclass(slots=True, frozen=True)")
    lines.append("class HighlightClip:")
    lines.append('    """A single clip in the highlight."""')
    lines.append("    start: float")
    lines.append("    end: float")
    lines.append("    score: float")
    lines.append("    reason: str")
    lines.append("")
    lines.append("")
    lines.append("    @property")
    lines.append("    def duration(self) -> float:")
    lines.append("        return self.end - self.start")
    lines.append("")
    lines.append("")
    lines.append("")
    lines.append("@dataclass(slots=True, frozen=True)")
    lines.append("class HighlightResult:")
    lines.append('    """Result of highlight generation."""')
    lines.append("    clips: list[HighlightClip]")
    lines.append("    total_duration: float")
    lines.append("")
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Written: {path}")


if __name__ == "__main__":
    write_analysis()
    write_highlight()
    print("Done!")